Repository 5h0bh4nk/FizzBuzz-Hacktoberfest-2022, pull requests merged in 2021-10, with the labels that each got.

#3 added C program
  C/fizzbuzz.c
Labels: hacktoberfest-accepted

#15 Added a code to cpp folder
  C++/a.out
  C++/youGetOnly100.cpp
Labels: hacktoberfest-accepted

#14 Added a new C++ fizzbuzz code
  C++/fizzbuzz4.cpp
Labels: hacktoberfest-accepted

#35 Added fizzbuzz divisiblity in CPP
  C++/fizzbuzz_divisibilty.cpp
Labels: hacktoberfest-accepted, top

#36 New Language : Dart
  Dart/FirstCode.dart
Labels: hacktoberfest-accepted, new language

#37 Added Code for FIzzBuzz
  C++/FizzBuzz5.cpp
  C++/FizzBuzz_without_mod_and_counting.cpp
Labels: hacktoberfest-accepted

#56 added fizzbuzz obfuscated in C++
  BrainFuck/FizzBuzz_new.bf
  C++/FizzBuzz_Obfuscated.cpp.cpp
Labels: hacktoberfest-accepted, top

#58 added fizzBuzz using segment tree
  C++/FizzBuzz_SegmentTree.cpp
Labels: hacktoberfest-accepted, top

#59 added fizzBuzz with branchless logic
  C++/FizzBuzz_branchless_logic.cpp
Labels: hacktoberfest-accepted, top

#60 added haskell version of fizzbuzz
  Haskell/fizzbuzz.hs
Labels: new language

#61 Added fizzBuzz code in D Language
  D/FizzBuzz.d
Labels: hacktoberfest-accepted, new language

#62 + Java with switch case solution
  JAVA/FizzBuzzWithSwitchCase.java
Labels: hacktoberfest-accepted

#63 Added FizzBuzz in Crystal Language
  Crystal/fizzbuzz.cr
Labels: new language

#65 added fizzbuzz in Clojure(.clj)
  Clojure/fizzbuzz.clj
Labels: hacktoberfest-accepted, new language

#64 Added some elixir fizz buzz solutions
  Elixir/fizz_buzz.exs
  Elixir/fizz_buzz_obfuscated.exs
  Elixir/fizz_buzz_one_liner.exs
Labels: hacktoberfest-accepted, new language, top

#75 FizzBuzz Implementation in PHP
  PHP/Fizz.php
Labels: hacktoberfest-accepted

#146 Added FizzBuzz in ArnoldC
  ArnoldC/Fizzbuzz.arnoldc
Labels: hacktoberfest-accepted, new language, Esolang

#147 Add TCL solution
  Tcl/Fizzbuzz.tcl
Labels: hacktoberfest-accepted, new language

#145 fizzbuzz(naive soultion)
  R/fizzbuzz(Vectorised Solution Using case_when).r
Labels: hacktoberfest-accepted

#149 Create fizz_buzz.elm
  elm/fizz_buzz.elm
Labels: hacktoberfest-accepted

#150 Created a FizzBuzz in GUI with Tkinter
  Python/FizzBuzz_Tkinter.py
Labels: hacktoberfest-accepted

#151 Fixxbuxx array mode
  javascript/fizzbuzz_ArrayMode.js
Labels: hacktoberfest-accepted
